cplanetsite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path("game/", include("game.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", views.home, name="home"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
   urlpatterns.append(path("__reload__/", include("django_browser_reload.urls")))

game/urls.py
from django.urls import path
from . import views

app_name = "game"
urlpatterns = [
    path("", views.index, name="index"),
    path("player/<int:player_id>/", views.player, name="player"),
    path(
        "player/<int:player_id>/daily_meal_log",
        views.daily_meal_log,
        name="daily_meal_log",
    ),
    path("player/<int:player_id>/feedback", views.feedback, name="feedback"),
    path("starter_animal", views.select_starter_animal, name="starter_animal"),
    path("library", views.Library.as_view(), name="library"),
]

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <title>{% block title %}Compassion Planet Game{% endblock %}</title>
</head>

<body>
    <main>
        <div class="container py-5">
            {% block content %}
            {% endblock %}
        </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"></script>
    {% block scripts %}
    {% endblock %}
</body>

</html>

templates/base_no_container.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'favicon.ico' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'game/css/styles.css' %}"/>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous">
	</script>
    {% block head %}
    {% endblock %}
    <title>{% block title %}Compassion Game{% endblock %}</title>
</head>

<body style="min-height:100vh; width:100%">
	<main>
		{% block pre_navbar_content %}
		{% endblock%}
		<div style="width:100%; height:100%;">
		{% include 'navbar.html' %}
		{% include 'messages.html' %}
		{% include 'one_hidden_toast.html' %}
		{% if user.is_authenticated and not user.is_email_verified and user.is_subscribed_meal_log_mail %}
			<div class="alert alert-info" role="alert" style="padding:5px 20px; text-align:center; margin-bottom:0px;">
				<small>Please check your email and follow the instructions to verify your account.
					<button type="button" id="resend-email-btn"
						class="btn btn-outline-primary btn-sm" 
						onclick="resendVerifyEmail()">Resend</button>
					<a class="btn btn-outline-secondary btn-sm" href="{% url 'change_email' %}" 
						role="button">Change email
					</a>
				</small> 
			</div>
		{% endif %}
		{% block content %}
		{% endblock %}
		</div>
	</main>

	{% if messages %}
	<script>
		var toastElList = [].slice.call(document.querySelectorAll('.dj-message'))
		var toastList = toastElList.map(function (toastEl) {
		  return new bootstrap.Toast(toastEl)
		})
		toastList.forEach((toast) => toast.show()) 
	</script>
	{% endif %}
	{% if user.is_authenticated and not user.is_email_verified and user.is_subscribed_meal_log_mail %}
	<script type="text/javascript">
		const resendVerifyEmailBtn = document.getElementById("resend-email-btn")
		const dynamicToastEle = document.getElementById('one-hidden-toast')
		const topicEle = document.getElementById('one-hidden-toast-topic')
		const resendVerifyEmail = async () => {
			resendVerifyEmailBtn.setAttribute("disabled",true)
			const response = await fetch("{% url 'resend_verify' %}", 
				options={ headers: {
					'Content-Type': 'text/plain'} 
			})
			let topic = "Success"
			let msg = ""
			try {
				if (!response.ok) throw Error(response.status) 
				msg = await response.text()
				topicEle.classList.remove("text-danger")
				topicEle.classList.add("text-success")
			}
			catch {
				topic = `Error ${response.status} ${response.statusText}`
				msg = `Error sending email. Try again and submit feedback if problem persists.`
				topicEle.classList.remove("text-success")
				topicEle.classList.add("text-danger")
			}
			finally {
				topicEle.innerHTML = topic
				document.getElementById('one-hidden-toast-msg').innerHTML = msg
				new bootstrap.Toast(dynamicToastEle).show()
				resendVerifyEmailBtn.removeAttribute("disabled")
			}
		}
	</script>
	{% endif %}
	{% block scripts %}
	{% endblock %}
</body>
</html>

templates/chick_header.html
<div class="d-flex flex-wrap align-items-center mb-4">
    <h1 class="me-4">{{headingtext}}</h1>
    <img src="{% static 'game/dalle_nerdy_chick.png' %}" style="height: 45px; max-width:45px"/>
</div>

templates/def_vegan_meal_snip.html
A <b>vegan meal</b> does not contain meat, dairy, eggs, honey, or 
any other product derived from an animal.

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/fullscreen_img_box.html
<div style="
    position:fixed;
    top:0;
    left:0;
    width: 100%;
    height: 100%;
    background-repeat: no-repeat; 
    background-size: cover;
    overflow-y: scroll;
    background-image: url('{{props.img_url}}')">
    <div class="container py-5"> 
        {{props.children}}
    </div>
</div>

templates/fun_msg_box.html
<div class="border border-dark rounded bg-light">
    <div class="border border-info border-4 px-3 py-2 rounded">
        {{props.children}}
    </div>
</div>

templates/home.html
{% extends 'base_no_container.html' %}
{% block title %}Home{% endblock %}
{% block content %}
{% load static %}
<div class="fullscreen-bg-img" 
    style="background-image: url('{% static 'game/dalle_video_game_art_nature_background_miyazaki.png' %}')">
    <div class="container py-5"> 
        <div class="row g-4 mb-5">
            <div class="col-md">
                <div class="border border-dark rounded bg-light">
                    <div class="border border-info border-4 px-3 py-2 rounded">
                        <h1>Welcome</h1>
                        <p>
                            Join a community of players adopting a more compassionate plant-based diet, 
                            one meal at a time.
                        </p>
                        <div class="d-flex justify-content-end gap-3 flex-wrap"> 
                            <a class="btn btn-primary" href="{% url 'signup' %}" role="button">Get Started</a>
                            <a class="btn btn-secondary" href="{% url 'login' %}" role="button">Login</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md">
                <div class="border border-dark rounded bg-light">
                    <div class="border border-info border-4 px-4 py-3 rounded">
                    {% include "game/community_bulletin_snip.html" %}
                    </div>
                </div>
            </div>
        </div>
        <div class="border border-dark rounded bg-light mx-auto" style="max-width:700px">
            <div class="border border-info border-4 px-4 pt-4 rounded">
                <div class="d-flex flex-wrap align-items-center mb-3">
                    <h2 class="me-4 my-0">The Rundown</h2>
                    <img src="{% static 'game/dalle_nerdy_chick.png' %}" style="height: 45px; max-width:45px"/>
                </div>
                <div class="mx-auto px-3">
                    <img class="rounded mx-auto d-block demo-gif mb-3"
                        src="{% static 'img/start-animal-small.gif' %}"
                        alt="Starter animal gif"
                        />
                    <p>
                        Compassion Game is <strong>for anyone who wants to adopt a more compassionate diet</strong> 
                        no matter what size of a step they wish to begin with.<br> 
                    </p>
                    <img class="rounded mx-auto d-block demo-gif mb-3"
                        src="{% static 'img/meal-log.gif' %}"
                        alt="Meal log gif"
                        />
                    <p>
                        With just <strong>one minute a day</strong>, log meals to earn  
                        earn rewards for challenges while contributing to a real impact that grows with the community.     
                    </p>
                    <img class="rounded mx-auto d-block demo-gif mb-3"
                        src="{% static 'img/badges.gif' %}"
                        alt="Badges gif"
                    />
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/mail_base.html
{% load static %}
{% load game_extras %}
{% comment %} https://github.com/leemunroe/responsive-html-email-template/blob/master/email.html {% endcomment %}
<!doctype html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Compasison Planet</title>
<style>
  /* -------------------------------------
      GLOBAL RESETS
  ------------------------------------- */
  
  /*All the styling goes here*/
  
  img {
    border: none;
    -ms-interpolation-mode: bicubic;
    max-width: 100%; 
  }

  body {
    background-color: #f6f6f6;
    font-family: sans-serif;
    -webkit-font-smoothing: antialiased;
    font-size: 14px;
    line-height: 1.4;
    margin: 0;
    padding: 0;
    -ms-text-size-adjust: 100%;
    -webkit-text-size-adjust: 100%; 
  }

  table {
    border-collapse: separate;
    mso-table-lspace: 0pt;
    mso-table-rspace: 0pt;
    width: 100%; }
    table td {
      font-family: sans-serif;
      font-size: 14px;
      vertical-align: top; 
  }

  /* -------------------------------------
      BODY & CONTAINER
  ------------------------------------- */

  .body {
    background-color: #f6f6f6;
    width: 100%; 
  }

  /* Set a max-width, and make it display as block so it will automatically stretch to that width, but will also shrink down on a phone or something */
  .container {
    display: block;
    margin: 0 auto !important;
    /* makes it centered */
    max-width: 580px;
    padding: 10px;
    width: 580px; 
  }

  /* This should also be a block element, so that it will fill 100% of the .container */
  .content {
    box-sizing: border-box;
    display: block;
    margin: 0 auto;
    max-width: 580px;
    padding: 10px; 
  }

  /* -------------------------------------
      HEADER, FOOTER, MAIN
  ------------------------------------- */
  .main {
    background: #ffffff;
    border-radius: 3px;
    width: 100%; 
  }

  .wrapper {
    box-sizing: border-box;
    padding: 20px; 
  }

  .content-block {
    padding-bottom: 10px;
    padding-top: 10px;
  }

  .footer {
    clear: both;
    margin-top: 10px;
    text-align: center;
    width: 100%; 
  }
    .footer td,
    .footer p,
    .footer span,
    .footer a {
      color: #999999;
      font-size: 12px;
      text-align: center; 
  }

  /* -------------------------------------
      TYPOGRAPHY
  ------------------------------------- */
  h1,
  h2,
  h3,
  h4 {
    color: #000000;
    font-family: sans-serif;
    font-weight: 400;
    line-height: 1.4;
    margin: 0;
    margin-bottom: 10px; 
  }

  h1 {
    font-size: 35px;
    font-weight: 300;
    text-align: center;
    text-transform: capitalize; 
  }

  p,
  ul,
  ol {
    font-family: sans-serif;
    font-size: 14px;
    font-weight: normal;
    margin: 0;
    margin-bottom: 15px; 
  }
    p li,
    ul li,
    ol li {
      list-style-position: inside;
      margin-left: 5px; 
  }

  a {
    color: #3498db;
    text-decoration: underline; 
  }

  /* -------------------------------------
      BUTTONS
  ------------------------------------- */
  .btn {
    box-sizing: border-box;
    width: 100%; }
    .btn > tbody > tr > td {
      padding-bottom: 15px; }
    .btn table {
      width: auto; 
  }
    .btn table td {
      background-color: #ffffff;
      border-radius: 5px;
      text-align: center; 
  }
    .btn a {
      background-color: #ffffff;
      border: solid 1px #3498db;
      border-radius: 5px;
      box-sizing: border-box;
      color: #3498db;
      cursor: pointer;
      display: inline-block;
      font-size: 14px;
      font-weight: bold;
      margin: 0;
      padding: 12px 25px;
      text-decoration: none;
      text-transform: capitalize; 
  }

  .btn-primary table td {
    background-color: #3498db; 
  }

  .btn-primary a {
    background-color: #3498db;
    border-color: #3498db;
    color: #ffffff; 
  }

  /* -------------------------------------
      OTHER STYLES THAT MIGHT BE USEFUL
  ------------------------------------- */
  .last {
    margin-bottom: 0; 
  }

  .first {
    margin-top: 0; 
  }

  .align-center {
    text-align: center; 
  }

  .align-right {
    text-align: right; 
  }

  .align-left {
    text-align: left; 
  }

  .clear {
    clear: both; 
  }

  .mt0 {
    margin-top: 0; 
  }

  .mb0 {
    margin-bottom: 0; 
  }

  .preheader {
    color: transparent;
    display: none;
    height: 0;
    max-height: 0;
    max-width: 0;
    opacity: 0;
    overflow: hidden;
    mso-hide: all;
    visibility: hidden;
    width: 0; 
  }

  .powered-by a {
    text-decoration: none; 
  }

  hr {
    border: 0;
    border-bottom: 1px solid #f6f6f6;
    margin: 20px 0; 
  }

  /* -------------------------------------
      RESPONSIVE AND MOBILE FRIENDLY STYLES
  ------------------------------------- */
  @media only screen and (max-width: 620px) {
    table.body h1 {
      font-size: 28px !important;
      margin-bottom: 10px !important; 
    }
    table.body p,
    table.body ul,
    table.body ol,
    table.body td,
    table.body span,
    table.body a {
      font-size: 16px !important; 
    }
    table.body .wrapper,
    table.body .article {
      padding: 10px !important; 
    }
    table.body .content {
      padding: 0 !important; 
    }
    table.body .container {
      padding: 0 !important;
      width: 100% !important; 
    }
    table.body .main {
      border-left-width: 0 !important;
      border-radius: 0 !important;
      border-right-width: 0 !important; 
    }
    table.body .btn table {
      width: 100% !important; 
    }
    table.body .btn a {
      width: 100% !important; 
    }
    table.body .img-responsive {
      height: auto !important;
      max-width: 100% !important;
      width: auto !important; 
    }
  }

  /* -------------------------------------
      PRESERVE THESE STYLES IN THE HEAD
  ------------------------------------- */
  @media all {
    .ExternalClass {
      width: 100%; 
    }
    .ExternalClass,
    .ExternalClass p,
    .ExternalClass span,
    .ExternalClass font,
    .ExternalClass td,
    .ExternalClass div {
      line-height: 100%; 
    }
    .apple-link a {
      color: inherit !important;
      font-family: inherit !important;
      font-size: inherit !important;
      font-weight: inherit !important;
      line-height: inherit !important;
      text-decoration: none !important; 
    }
    #MessageViewBody a {
      color: inherit;
      text-decoration: none;
      font-size: inherit;
      font-family: inherit;
      font-weight: inherit;
      line-height: inherit;
    }
    .btn-primary table td:hover {
      background-color: #34495e !important; 
    }
    .btn-primary a:hover {
      background-color: #34495e !important;
      border-color: #34495e !important; 
    } 
  }
</style>
{% block head %}
{% endblock %}
</head>
<body>
  <span class="preheader">{% block preheader %}{% endblock %}</span>
  <table role="presentation" border="0" cellpadding="0" cellspacing="0" class="body">
    <tr>
      <td>&nbsp;</td>
      <td class="container">
        <div class="content">
          <table align="center" border="0" cellpadding="0" cellspacing="0" 
            role="presentation" style="border-collapse:collapse;border-spacing:0px; margin-bottom: 10px;">
            <tbody>
                <tr>
                    <td style="width:64px; margin: 0 auto">
                        <img height="auto" 
                        src="{% email_page_domain %}{% static 'img/compassion-planet-logo.png' %}" 
                        style="border:0;display:block;outline:none;text-decoration:none; margin: 0 auto" 
                        width="64" />
                    </td>
                </tr>
              </tbody>
        </table>
          <table role="presentation" class="main">
            <tr>
              <td class="wrapper">
                <table role="presentation" border="0" cellpadding="0" cellspacing="0">
                  <tr>
                    <td>
                      {% block intro %}{% endblock %}
                      <table role="presentation" 
                        border="0" cellpadding="0" cellspacing="0" class="btn btn-primary">
                        <tbody>
                          <tr>
                            <td align="left">
                              <table role="presentation" border="0" cellpadding="0" 
                                cellspacing="0">
                                <tbody>
                                  <tr>
                                    <td> 
                                      {% block call_to_action %}
                                      {% endblock %}
                                    </td>
                                  </tr>
                                </tbody>
                              </table>
                            </td>
                          </tr>
                        </tbody>
                      </table>
                      {% block closing_body%}
                      {% endblock %}
                      Thanks for being here
                      <br>
                      Compassion Planet
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
          </table>
          <div class="footer">
            <table role="presentation" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td class="content-block">
                  {% block footer %}
                  {% endblock %}
                </td>
              </tr>
            </table>
          </div>
        </div>
      </td>
      <td>&nbsp;</td>
    </tr>
  </table>
</body>
</html>

templates/messages.html
{% for message in messages %}
<div class="position-fixed bottom-0 end-0 p-3" style="z-index:1" >
    <div class="dj-message toast hide" role="alert" 
        aria-live="assertive" 
        aria-atomic="true" 
        >
        <div class="toast-header" >
            {% with message.tags|lower as tags_low_case %}
            <strong class="me-auto text-{% if "err" in tags_low_case %}danger{% else %}{{ tags_low_case }}{% endif %}">
            {{message.tags|capfirst}}
            </strong>
            <button type="button" 
                class="btn-close" 
                data-bs-dismiss="toast" 
                aria-label="Close">
            </button>
            {% endwith %}
        </div>
        <div class="toast-body bg-light">
            {{message|safe}}
        </div>
    </div>
</div>
{% endfor %}

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light border-bottom border-secondary" 
    style="background-color: #e3f2fd;">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">
            <img src="{% static 'img/compassion-planet-logo.png' %}" alt="CP Logo" 
                class="d-inline-block align-text-top" 
                style="max-width: 40px; max-height:30px">
            Compassion Game
        </a>
        <button class="navbar-toggler" 
            type="button" 
            data-bs-toggle="collapse" 
            data-bs-target="#navbarNav" 
            aria-controls="navbarNav" 
            aria-expanded="false" 
            aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
            {% with request.resolver_match.view_name as view_name %}
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link {% if view_name == 'game:index' %}active{% endif %}" 
                        {% if view_name == 'game:index' %}aria-current="page"{% endif %}
                        href="{% url 'game:index' %}"
                    >Introduction</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if view_name == 'game:player' %}active{% endif %}" 
                        {% if view_name == 'game:player' %}aria-current="page"{% endif %} 
                        href="{% url 'game:player' user.player.id %}"
                    >Player</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if view_name == 'game:daily_meal_log' %}active{% endif %}" 
                        {% if view_name == 'game:daily_meal_log' %}aria-current="page"{% endif %} 
                        href="{% url 'game:daily_meal_log' user.player.id %}"
                    >Log meals</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if view_name == 'game:feedback' %}active{% endif %}" 
                        {% if view_name == 'game:feedback' %}aria-current="page"{% endif %}
                        href="{% url 'game:feedback' user.player.id %}"
                    >Feedback</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        More
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url 'game:library' %}">Library</a></li>
                        <li><a class="dropdown-item" href="https://gitlab.com/evanlesmez/compassion-planet-game">Open Source</a></li>
                        <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                    </ul>
                </li> 
                {% else %}
                <li class="nav-item">
                    <a class="nav-link {% if view_name == 'home' %}active{% endif %}" 
                        {% if view_name == 'home' %}aria-current="page"{% endif %}  
                        href="{% url 'home' %}"
                    >Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if view_name == 'signup' %}active{% endif %}" 
                        {% if view_name == 'singup' %}aria-current="page"{% endif %}  
                        href="{% url 'signup' %}"
                    >Signup</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if view_name == 'login' %}active{% endif %}" 
                        {% if view_name == 'login' %}aria-current="page"{% endif %}  
                        href="{% url 'login' %}"
                    >Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if view_name == 'game:library' %}active{% endif %}" 
                        {% if view_name == 'game:library' %}aria-current="page"{% endif %}  

                    <a class="nav-link" href="{% url 'game:library' %}">Library</a>
                </li>
                {% endif %}
            {% endwith %}
            </ul>  
        </div>
    </div>
</nav>

templates/one_hidden_toast.html
<div class="position-fixed bottom-0 end-0 p-3" style="z-index:1">
    <div id="one-hidden-toast" class="toast fade hide" role="alert" 
        aria-live="assertive" 
        aria-atomic="true" 
        >
        <div class="toast-header">
            <strong id="one-hidden-toast-topic" class="me-auto">
            </strong>
            <button type="button" 
                class="btn-close" 
                data-bs-dismiss="toast" 
                aria-label="Close">
            </button>
        </div>
        <div id="one-hidden-toast-msg" class="toast-body bg-light">
        </div>
    </div>
</div>

templates/vegan_hesitations_snippet.html
If you have hesitations about the impact a vegan diet has on 
your health and nutrition, the well-being of animals, climate change, or nature in general, please checkout the 
<a href="{% url 'game:library' %}" role="button">Library</a>