cplanetsite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path("game/", include("game.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", views.home, name="home"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
   urlpatterns.append(path("__reload__/", include("django_browser_reload.urls")))

game/urls.py
from django.urls import path
from . import views

app_name = "game"
urlpatterns = [
    path("", views.index, name="index"),
    path("player/<int:player_id>/", views.player, name="player"),
    path(
        "player/<int:player_id>/daily_meal_log",
        views.daily_meal_log,
        name="daily_meal_log",
    ),
    path("player/<int:player_id>/feedback", views.feedback, name="feedback"),
    path("starter_animal", views.select_starter_animal, name="starter_animal"),
    path("library", views.Library.as_view(), name="library"),
]

game/models.py
from email.policy import default
from pyexpat import model
from django.db import models
from pathlib import Path
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.urls import reverse

APP_NAME = Path(__file__).resolve().parent.stem


class User(AbstractUser):
    email = models.EmailField(unique=True)
    is_email_verified = models.BooleanField(default=False)
    is_subscribed_meal_log_mail = models.BooleanField(default=True)

class MeasurableUnit(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Measurable(models.Model):
    class Name(models.TextChoices):
        ANIMAL = "Animal"
        CARBON = "Carbon Emission"
        WATER_USAGE = "Water Usage"
        FOREST_AREA = "Forest Area"

    name = models.CharField(max_length=200, choices=Name.choices)
    rate_per_vegan_day = models.DecimalField(max_digits=10, decimal_places=4)
    unit = models.ForeignKey(MeasurableUnit, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} {self.unit}"


class Avatar(models.Model):
    class Type(models.TextChoices):
        COW = "cow"
        CHICKEN = "chicken"
        PIG = "pig"

    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to="avatars")
    type = models.CharField(max_length=200, choices=Type.choices)
    description = models.TextField(max_length=1000, default="")

    def __str__(self):
        return self.name


class Player(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ForeignKey(Avatar, on_delete=models.CASCADE, null=True)
    phone_number = PhoneNumberField(blank=True, default="")

    def __str__(self):
        return self.user.username


class Badge(models.Model):
    class Name(models.TextChoices):
        ANIMAL = "Animal Lover"
        CARBON = "Carbon"
        WATER_USAGE = "Water"
        FOREST_AREA = "Forest"

    measurable = models.ForeignKey(Measurable, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, choices=Name.choices)
    description = models.CharField(max_length=400)
    image = models.ImageField(upload_to="badges")
    tier = models.IntegerField()
    measurable_threshold_to_earn = models.DecimalField(max_digits=10, decimal_places=4)

    def __str__(self):
        return f"{self.name} {self.tier}"


class PlayerFeedback(models.Model):
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    feedback = models.TextField(max_length=1000)
    # disapointment_on_product_disapear score dropdown field
    rec_date = models.DateTimeField("date recorded", default=timezone.now)

    def __str__(self):
        return f"{self.player} at {self.rec_date}"


class DailyMealLog(models.Model):
    class Meta:
        db_table = f"{APP_NAME}_daily_meal_log"

    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    total_meal_count = models.PositiveIntegerField()
    vegan_meal_count = models.PositiveIntegerField()
    notes = models.TextField(max_length=1000, blank=True, default="")
    rec_date = models.DateTimeField("date recorded", default=timezone.now)

    def __str__(self):
        return f"{self.vegan_meal_count}/{self.total_meal_count} vegan score on {self.rec_date} "

    @property
    def was_recorded_today(self) -> bool:
        return timezone.now().date() == self.rec_date.date()

game/forms.py
from .models import DailyMealLog, PlayerFeedback, Player
from django.forms import ModelForm, IntegerField, HiddenInput


class PlayerStarterAnimalForm(ModelForm):
    class Meta:
        model = Player
        fields = ["avatar"]


class PlayerCreationForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for f in self.fields.keys():
            self.fields[f].widget.attrs.update({"class": "form-control"})

    class Meta:
        model = Player
        fields = ["phone_number"]


class DailyMealLogForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["total_meal_count"].widget.attrs.update(
            {"class": "form-control mb-3"}
        )
        self.fields["vegan_meal_count"].widget.attrs.update(
            {"class": "form-control mb-3"}
        )
        self.fields["notes"].widget.attrs.update(
            {"class": "form-control mb-3", "style": "height:100px;"}
        )

    class Meta:
        model = DailyMealLog
        fields = ["total_meal_count", "vegan_meal_count", "notes"]

    def clean(self):
 
        super(DailyMealLogForm, self).clean()
         
        total_meal_count = self.cleaned_data.get('total_meal_count')
        vegan_meal_count = self.cleaned_data.get('vegan_meal_count')
        if vegan_meal_count > total_meal_count:
            self._errors['vegan_meal_count'] = self.error_class([
                'Vegan meal count can\'t be bigger than total meal count.'])
 
        # return any errors if found
        return self.cleaned_data


class PlayerFeedbackForm(ModelForm):
    class Meta:
        model = PlayerFeedback
        fields = ["feedback"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["feedback"].widget.attrs.update(
            {
                "class": "form-control",
                "placeholder": "Leave feedback here please",
                "style": "height: 200px;",
            }
        )

game/views.py
from django.shortcuts import render, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import timezone
from django.views.generic import TemplateView
from typing import List
import itertools
from .models import Badge, DailyMealLog, Player, PlayerFeedback, Avatar
from .forms import DailyMealLogForm, PlayerFeedbackForm
from .queries import (
    get_fully_vegan_streak,
    get_partial_vegan_streak,
    get_player_badges,
    Streak,
    get_communal_measurables,
    CommunalMeasurable,
)
from typing import List


def index(request):
    communal_measurables: List[CommunalMeasurable] = get_communal_measurables()
    return render(
        request, "game/index.html", {"communal_measurables": communal_measurables}
    )


@login_required
def player(request, player_id):
    player = get_object_or_404(Player, pk=player_id)
    fully_v_streak: Streak = get_fully_vegan_streak(player_id=player.id)
    partial_v_streak: Streak = get_partial_vegan_streak(player_id=player.id)
    badges = get_player_badges(player_id=player.id)
    previous_badges = get_player_badges(player_id=player.id, day_limit=1)
    communal_measurables: List[CommunalMeasurable] = get_communal_measurables()
    try:
        latest_daily_meal_log = DailyMealLog.objects.filter(
            player=player, rec_date__lte=timezone.now()
        ).latest("rec_date")

    except ObjectDoesNotExist:
        latest_daily_meal_log = DailyMealLog(
            player=player, rec_date=timezone.datetime(2000, 1, 1)
        )
    badge_iter = itertools.groupby(badges, key=lambda b: b.tier)

    grouped_badges = {}
    for key, grp in badge_iter:
        if key in grouped_badges:
            grouped_badges[key] = grouped_badges[key] + list(grp)
            continue
        grouped_badges[key] = list(grp)
    newly_earned_badges = get_newly_earned_badges(previous_badges, badges)
    return render(
        request,
        "game/player.html",
        {
            "player": player,
            "fully_v_streak": fully_v_streak,
            "partial_v_streak": partial_v_streak,
            "grouped_badges": grouped_badges,
            "newly_earned_badges": newly_earned_badges,
            "communal_measurables": communal_measurables,
            "latest_daily_meal_log": latest_daily_meal_log,
        },
    )


def find(pred, iterable):
    for element in iterable:
        if pred(element):
            return element
    return None


def get_newly_earned_badges(previous_badges, new_badges):
    newly_earned_badges = []
    for new_badge in new_badges:
        previous_badge = find(lambda x: x.id == new_badge.id, previous_badges)
        is_earned_now = previous_badge.earned == False and new_badge.earned == True
        if is_earned_now:
            newly_earned_badges.append(new_badge)
    return newly_earned_badges


@login_required
def daily_meal_log(request, player_id):
    player = get_object_or_404(Player, pk=player_id)
    if player.user != request.user:
        resp = HttpResponse()
        resp.status_code = 403
        return resp

    fully_v_streak: Streak = get_fully_vegan_streak(player_id=player.id)
    partial_v_streak: Streak = get_partial_vegan_streak(player_id=player.id)
    try:
        daily_meal_log = DailyMealLog.objects.filter(
            player=player, rec_date__lte=timezone.now()
        ).latest("rec_date")

    except ObjectDoesNotExist:
        daily_meal_log = DailyMealLog(rec_date=timezone.datetime(2000, 1, 1))

    if request.method == "POST":
        method = request.POST.get("_method", "").lower()
        if method == "put":
            form = DailyMealLogForm(request.POST, instance=daily_meal_log)
            success_msg = "Meal log updated"

        else:
            daily_meal_log = DailyMealLog(player=player)
            form = DailyMealLogForm(request.POST, instance=daily_meal_log)
            success_msg = "Meals logged"

        if form.is_valid():
            form.save()
            messages.success(request, success_msg)
            return HttpResponseRedirect(reverse("game:player", args=(player.id,)))

    else:
        if daily_meal_log.was_recorded_today:
            form = DailyMealLogForm(instance=daily_meal_log)

        else:
            form = DailyMealLogForm()

    return render(
        request,
        "game/daily_meal_log.html",
        {
            "form": form,
            "player_id": player.id,
            "partial_v_streak": partial_v_streak,
            "fully_v_streak": fully_v_streak,
        },
    )


@login_required
def select_starter_animal(request):
    if request.method == "POST":
        player = Player.objects.get(user=request.user)
        avatar = get_object_or_404(Avatar, id=request.POST["avatar"])

        player.avatar = avatar
        player.save()
        return HttpResponseRedirect(
            reverse(
                "game:index",
            )
        )

    avatars = Avatar.objects.all()
    return render(request, "game/starter_animal.html", {"avatars": avatars})


@login_required
def feedback(request, player_id):
    player = get_object_or_404(Player, pk=player_id)
    if player.user != request.user:
        resp = HttpResponse()
        resp.status_code = 403
        return resp

    if request.method == "POST":
        player_feedback = PlayerFeedback(player=player)
        form = PlayerFeedbackForm(request.POST, instance=player_feedback)
        if form.is_valid():
            form.save()
            messages.success(request, "Thanks for the feedback!")
            return HttpResponseRedirect(reverse("game:player", args=(player.id,)))
    else:
        form = PlayerFeedbackForm()

    return render(
        request,
        "game/player_feedback.html",
        {"form": form, "player_id": player.id},
    )


class Library(TemplateView):
    template_name = "game/library.html"

game/templates/game/community_bulletin_snip.html
{% load humanize %}
{% load game_extras %}
<div>
    <h2 class="mb-3">Community Bulletin</h2>
    <p>Our total impact contributed to by every player.</p>
    {% include 'game/community_stats_snip.html' %}
</div>

game/templates/game/community_stats_snip.html
{% load humanize %}
{% load game_extras %}
{% for cm in communal_measurables %}
<div> 
    <strong>{{cm.progress|intcomma}} </strong> 
    {% if cm.name|lower == "animal" %}
    <strong>{{cm.name|lower |pluralize_noun:cm.progress}}</strong>
    {% else %}
    {{cm.unit|pluralize_noun:cm.progress}} of
    <strong>
        {% if cm.name|lower == "carbon emission" %}
        {{cm.name|lower |pluralize_noun:cm.progress}}
        {% else %}
        {{cm.name|lower}}
        {% endif %}
    </strong>  
    {% endif %}
    saved
    {{cm.emoji}}
</div>
{% endfor %}

game/templates/game/daily_meal_log.html
{% extends "base_no_container.html" %}
{% load static %}
{% block content %}
<div class="fullscreen-bg-img" style="background-image: url({% static 'game/dalle_grocery_market.png' %})">
    <div class="container py-5">
        {% include "form_errors.html" %}
        <div class="row g-4 mb-5">
            <div class="col-md-6">
                <div class="border border-dark rounded">
                    <div class="bg-light rounded py-3 px-4 border border-4 border-info">
                        <h1>Meal Log</h1>
                        <p>{% now "M jS, Y"%}</p>
                        <form id="meal_form" action="{% url 'game:daily_meal_log' player_id %}" 
                        method="post" onsubmit="disableBtn()">
                        {% csrf_token %}
                            {% if form.total_meal_count.value is not None%}
                            <input type="hidden" name="_method" value="put" />
                            {% endif %}
                            <div class="text-danger">{{form.total_meal_count.errors}}</div>
                            <div class="form-floating mb-3">
                                {{form.total_meal_count}}
                                <label for="{{form.total_meal_count.id_for_label}}">{{form.total_meal_count.label}}</label> 
                            </div>
                            <div class="text-danger">{{form.vegan_meal_count.errors}}</div>
                            <div class="form-floating">
                                {{form.vegan_meal_count}}
                                <label for="{{form.vegan_meal_count.id_for_label}}">{{form.vegan_meal_count.label}}</label> 
                            </div>
                            <div class="form-floating">
                                {{form.notes}}
                                <label for="{{form.notes.id_for_label}}">What did you eat? (optional)</label> 
                            </div>
                                <a href="#guidance">Need guidance?</a> 
                            <div class="d-flex justify-content-center pt-2">
                                <button type="submit" class="btn btn-primary" id="id_submit"/>
                                {% if form.total_meal_count.value is None %}
                                Send it
                                {% else %}
                                Update
                                {% endif %}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="border border-dark rounded">
                    <div class="bg-light rounded py-3 px-4 border border-4 border-info">
                        <h2>Streaks</h2>
                        {% include "game/streaks_snippet.html" %}
                    </div>
                </div>
            </div>
        </div>
        <div class="d-inline-block border border-dark rounded" id="guidance" style="max-width:750px">
            <div class="bg-light rounded py-3 px-4 border border-4 border-info">
                <div class="d-flex flex-wrap align-items-center mb-4">
                    <h1 class="me-4">Guide</h1>
                    <img src="{% static 'game/dalle_nerdy_chick.png' %}" style="height: 45px; max-width:45px"/>
                </div>
                <dl>
                    {% include 'def_vegan_meal_snip.html' %}
                    <dd>What counts as a "meal" is up to you but we recommend keeping it simple.</dd>
                    <dd>It is more important to get a sense of sittings in a day you consumed fully vegan foods and drinks out 
                        of the total sittings that day.<dd>
                    <br>
                    <dd>
                        This community depends on your <b>honesty</b>.
                        If you did not eat any vegan meals, missed a day, or messed up an entry, don't sweat it.</dd>
                    <dd>Try again.</dd>
                    <br>
                    <dd>Remember that every meal you abstain from animal products saves animals and 
                        vital resources. Even if you do not identify as vegan, <b>each meal</b> is still an 
                        <b>opportunity to choose compassion</b>.
                    </dd>
                </dl>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block scripts %}
<script>
    const id_tmc = "id_total_meal_count"
    var eleTotalMealCnt = document.getElementById(id_tmc).addEventListener("change", updateVeganMealCountField)
    function updateVeganMealCountField() {
        var eleTotalMealCnt = document.getElementById(id_tmc)
        var eleVeganMealCnt = document.getElementById("id_vegan_meal_count");
        eleVeganMealCnt.setAttribute("max", eleTotalMealCnt.value)

    }
  
    const disableBtn = () => {
        document.getElementById('id_submit').setAttribute("disabled",true);
    }
    
   updateVeganMealCountField() 

</script>
{% endblock %}

game/templates/game/index.html
{% extends "base_no_container.html" %}
{% block content%}
{% load static %}
<div class="fullscreen-bg-img" style="background-image: url('{% static 'game/dalle_lit_up_town.png' %}')">
    <div class="container py-5"> 
        <div class="row g-4 mb-5">
            <div class="col-md">
                <div class="border border-dark rounded bg-light" style="max-width:750px">
                    <div class="border border-info border-4 px-3 py-2 rounded">
                        <div class="d-flex flex-wrap align-items-center mb-2">
                            <h1 class="me-4">First steps</h1>
                            <img src="{% static 'game/dalle_nerdy_chick.png' %}" style="height: 45px; max-width:45px"/>
                        </div>
                        <p>Welcome!<br>
                        Our goal is to motivate you along your journey of adopting a more compassionate diet.<br>
                        It only takes one minute a day to play.</p>
                        <ol class="mb-4">
                            <li>
                                <div class="mb-1"><a href="{% url 'game:daily_meal_log' user.player.id %}">Log meals</a> each day.  
                                    Record how many meals were <a href="#vegan-def"><i>vegan</i></a> out of the total.
                                </div>
                                <img class="rounded mx-auto d-block demo-gif mb-3"
                                    src="{% static 'img/meal-log.gif' %}"
                                    alt="Meal log gif"/>
                            </li>
                            <li>
                                <div class="mb-1">
                                    Track progress towards badges on your 
                                    <a href="{% url 'game:player' user.player.id %}">player</a> page.
                                    Each badge is earned through reductions of harm in the real world, such as saving animals.
                                </div>

                                <img class="rounded mx-auto d-block demo-gif mb-3"
                                    src="{% static 'img/badges.gif' %}"
                                    alt="Badges gif"/>
                            </li>
                            <li>Check the <a href="#community-bulletin-container">Community Bulletin</a> intermittently to see
                                the growth in impact of the entire player base combined.
                            </li>
                        </ol>
                        <div class="mb-3">
                        {% with user.player as player %}
                            {% include 'game/meal_log_btn_snippet.html' %}
                        {% endwith %}
                        </div>
                        <small id="vegan-def">
                            {% include "def_vegan_meal_snip.html" %}
                            In comparison with a traditional omnivorous meal, a vegan meal <strong>reduces demand</strong> for
                            <strong>animal suffering, carbon emissions, forest area</strong> and <strong>water usage</strong>.
                            These reductions are achievable while still enjoying healthy, tasty, and affordable dishes.
                            <br>
                            <br>
                            {% include "vegan_hesitations_snippet.html" %}
                        </small>
                    </div>
                </div>
            </div>
            <div class="col-md">
                <div class="border border-dark rounded bg-light" id="community-bulletin-container">
                    <div class="border border-info border-4 px-4 py-3 rounded">
                    {% include "game/community_bulletin_snip.html" %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

game/templates/game/meal_log_btn_snippet.html
{% if user.player == player and not latest_daily_meal_log.was_recorded_today %}
<div class="d-flex justify-content-center py-2">
    <a role="button" href="{% url 'game:daily_meal_log' player.id %}" class="btn btn-lg btn-primary" />Log today's meals</a>
</div>
{% endif %}

game/templates/game/player_feedback.html
{% extends "base_no_container.html" %}
{% load static %}
{% block content %}
<div class="fullscreen-bg-img" style="background-image: url({% static 'game/dalle_video_game_art_nature_background_miyazaki.png'%}">
    <div class="container py-5">
        {% include "form_errors.html" %}
        <div class="d-flex flex-wrap flex-shrink-0 justify-content-center">
            <div class="p-3">
                <div class="border border-dark bg-light rounded">
                    <div class="border border-info border-4 rounded py-2 px-3">
                        <div class="d-flex flex-wrap align-items-center">
                            <h1 class="me-3 my-2">Feedback</h1>
                            <img src="{% static 'game/dalle_nerdy_chick.png' %}" style="height: 45px; max-width:45px"/>
                        </div>
                        <p>
                            Have any problems or suggestions?<br>
                            How disappointed would you be if this site disappeared tomorrow?<br>
                            Let us know below!
                        </p>
                    </div>
                </div>
            </div>
            <div class="p-3">
                <div class="border border-dark bg-light rounded">
                    <div class="border border-info border-4 rounded">
                    <form action="{% url 'game:feedback' player_id %}" method="post">
                        {% csrf_token %}
                        <div class="form-floating">
                            {{form.feedback}}
                            <label for="floatingTextarea">{{form.feedback.label}}</label>
                        </div>
                        <div class="d-flex justify-content-center py-4 px-3">
                            <button type="submit" class="btn btn-primary" />Send it</button>
                        </div>
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

game/templates/game/starter_animal.html
{% extends 'base_no_container.html' %}
{% load static %}
{% block pre_navbar_content %}
<div class="modal" id="animal-modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class='border border-dark rounded'>
                <div class='border border-info border-3 rounded'>
                    <div class="modal-header" style="background-color: #e3f2fd;">
                        <h2 id="animal-name" class="modal-title">Name</h2>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="mx-auto" style="max-height:250px;max-width:225px;">
                            <img id="animal-img"src="" class="img-fluid rounded-5" >
                        </div>
                        <hr>
                        
                        <p id="animal-description">Animal description</p>
                        <h4>Type</h4>
                        <p id="animal-type">Animal type</p>
                    </div>
                    <div class="modal-footer" style="background-color: #e3f2fd;">
                        <div class="" style="width:100%">Are you sure about your choice?</div>
                        <form action="{% url 'game:starter_animal' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" id="animal-id" name="avatar" value="">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                            <button type="submit" class="btn btn-primary">Yes</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block content %}
<style>
    @keyframes wiggle {
        0% {
            transform: rotate(0deg);
        }
        93% {
            transform: rotate(0deg);
        }
        94% {
            transform: rotate(3deg);
        }
        95% {
            transform: rotate(-3deg);
        }
        96% {
            transform: rotate(3deg);
        }
        97% {
            transform: rotate(-3deg);
        }
        98% {
            transform: rotate(3deg);
        }
        99% {
            transform: rotate(-3deg);
        }
        100% {
            transform: rotate(0deg);
        }
    }
</style>
<div class="fullscreen-bg-img" style="background-image: url('{% static 'game/dalle_video_game_art_nature_background_miyazaki.png' %}'">
    <div class ="container py-5">
        <div class = 'row pb-5 justify-content-around' >
        {% for a in avatars %}
            <div class="col-4 justify-content-center align-items-center px-md-5 px-sm-4" style="animation: wiggle {{forloop.counter}}s infinite;">
                <div id="{{a.id}}" class="animal-capsule" style="width:100%; min-width:20px; max-width:200px">
                    <img src="{% static 'game/light_blue_miyazaki_starter_animal_capsule.png' %}" class="img-fluid mx-auto"/>
                </div>
            </div>
        {% endfor %}
        </div>
        <div class="d-inline-block border border-dark rounded mx-md-5 mt-5">
            <div class="d-flex bg-light rounded py-2 px-3 border border-4  border-info">
                <p>Choose your starter animal.</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block scripts %}
{% get_media_prefix as MEDIA_PREFIX %}
{% load game_extras %}
{{ avatars|qs_to_list|json_script:"avatars" }}
<script>
    const avatars = JSON.parse(document.getElementById('avatars').textContent);
    const animalModal = new bootstrap.Modal(document.getElementById('animal-modal'));
    const animalCapsules = document.getElementsByClassName('animal-capsule');
    
    for (let i = 0;  i < animalCapsules.length; i++) {
        const animEle = animalCapsules[i]
        animEle.addEventListener('click', (event) => {
            const ava = avatars.find(x => x.id.toString() == animEle.id)
            document.getElementById("animal-name").innerHTML = ava.name
            document.getElementById("animal-img").src = {{MEDIA_PREFIX}} + ava.image
            document.getElementById("animal-description").innerHTML = ava.description
            document.getElementById('animal-type').innerHTML = ava.type
            document.getElementById('animal-id').value = ava.id
            setTimeout(() => animalModal.show(), 20)
        })
    }
</script>
{% endblock %}

game/templates/game/streaks_snippet.html
{% load game_extras %}

{% if partial_v_streak.days is 0 %}

<div>
    <p>No active streaks but don't sweat it 😅
        <br>
    Log a vegan meal today to begin a new one.
    </p>
</div>
{% else %}
<div>
    <p>
        Keep your streaks going! 
    </p>
    {% if fully_v_streak.days > 0 %}
    <p>
        <strong>{{fully_v_streak.days}} day{{fully_v_streak.days|pluralize}} </strong> 
        all vegan 🚀
    </p>
    {% endif %}
    {% if fully_v_streak.days is not partial_v_streak.days %}
    <p>
        <strong>{{partial_v_streak.days}} day{{partial_v_streak.days|pluralize}} </strong> 
        at least one vegan meal 🔥
    </p>
    {% endif %}
</div>
{% endif %}